steps:

  - id: eclint
    name: "e53e225/editorconfig-checker"
    
  - id: go_version
    name: "gcr.io/cloud-builders/go"
    args: ["version"]
    env: ["GOPATH=."]
    
  - id: go_linter
    name: "golangci/golangci-lint"
    args: ["golangci-lint","run"]
    
  - id: "Instalação do App SomaNumeros"
    name: 'gcr.io/cloud-builders/go'
    args: ['install', 'soma']
    env: ['GOPATH=.']
    
  - id: 'Executando o Teste Unitário do App SomaNumeros'
    name: 'gcr.io/cloud-builders/go'
    args: ['test', '-v','./...']
    env: ['GOPATH=.']